# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize_cpp <- function(country, configFile, runtimeDir) {
    invisible(.Call('_openalpR_initialize_cpp', PACKAGE = 'openalpR', country, configFile, runtimeDir))
}

#' Closes the connection to the ANPR handler.
#'
#' MUST BE RUN AFTER FINISHING NUMBER PLATE RECOGNITION.
#'
#' @return None
#' @export
close <- function() {
    invisible(.Call('_openalpR_close', PACKAGE = 'openalpR'))
}

#' Checks whether the number plate recogniser has been successfully loaded.
#'
#' @return A boolean indicating whether ANPR requests can be made or not.
#' @export
is_loaded <- function() {
    .Call('_openalpR_is_loaded', PACKAGE = 'openalpR')
}

recognize_file_cpp <- function(imageFile) {
    .Call('_openalpR_recognize_file_cpp', PACKAGE = 'openalpR', imageFile)
}

#' Changes the country.
#'
#' @param country 'eu' or 'us'.
#' @return None.
set_country <- function(country) {
    invisible(.Call('_openalpR_set_country', PACKAGE = 'openalpR', country))
}

#' Not entirely sure what this does...
#'
#' @param A string representing something...
#' @return None.
set_prewarp <- function(prewarp) {
    invisible(.Call('_openalpR_set_prewarp', PACKAGE = 'openalpR', prewarp))
}

#' Not entirely sure what this does...
#'
#' @param A string representing something...
#' @return None.
set_default_region <- function(default_region) {
    invisible(.Call('_openalpR_set_default_region', PACKAGE = 'openalpR', default_region))
}

#' Sets whether the region should be detected automatically or not.
#'
#' I'm unsure if region is the same as country. 
#'
#' @param detect_region Whether to automatically detect the region or not.
#' @return None.
setDetectRegion_cpp <- function(detect_region) {
    invisible(.Call('_openalpR_setDetectRegion_cpp', PACKAGE = 'openalpR', detect_region))
}

#' Sets how many candidates to return.
#'
#' @param top_n How many values to return. Default is 10.
#' @return None.
set_top_n <- function(top_n) {
    invisible(.Call('_openalpR_set_top_n', PACKAGE = 'openalpR', top_n))
}

#' Returns the openalpr library version number.
#'
#' @return The version number as a string
#' @export
get_version <- function() {
    .Call('_openalpR_get_version', PACKAGE = 'openalpR')
}

