# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

initialize <- function(country, configFile, runtimeDir) {
    .Call(`_openalpR_initialize`, country, configFile, runtimeDir)
}

dispose <- function(nativeAlpr) {
    invisible(.Call(`_openalpR_dispose`, nativeAlpr))
}

isLoaded <- function(nativeAlpr) {
    .Call(`_openalpR_isLoaded`, nativeAlpr)
}

recognizeFile <- function(nativeAlpr, imageFile) {
    .Call(`_openalpR_recognizeFile`, nativeAlpr, imageFile)
}

freeJsonMem <- function(ptr) {
    invisible(.Call(`_openalpR_freeJsonMem`, ptr))
}

recognizeArray <- function(nativeAlpr, buf, len) {
    .Call(`_openalpR_recognizeArray`, nativeAlpr, buf, len)
}

setCountry <- function(nativeAlpr, country) {
    invisible(.Call(`_openalpR_setCountry`, nativeAlpr, country))
}

setPrewarp <- function(nativeAlpr, prewarp) {
    invisible(.Call(`_openalpR_setPrewarp`, nativeAlpr, prewarp))
}

setDefaultRegion <- function(nativeAlpr, default_region) {
    invisible(.Call(`_openalpR_setDefaultRegion`, nativeAlpr, default_region))
}

setDetectRegion <- function(nativeAlpr, detect_region) {
    invisible(.Call(`_openalpR_setDetectRegion`, nativeAlpr, detect_region))
}

setTopN <- function(nativeAlpr, top_n) {
    invisible(.Call(`_openalpR_setTopN`, nativeAlpr, top_n))
}

getVersion <- function(nativeAlpr) {
    .Call(`_openalpR_getVersion`, nativeAlpr)
}

